# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/src/main/cpp/lib/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/arm64-v8a/octomap/arm64-v8a/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/arm64-v8a/octomap/arm64-v8a/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/arm64-v8a/octomap/arm64-v8a/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/arm64-v8a/octomap/arm64-v8a/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/armeabi-v7a/octomap/armeabi-v7a/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/armeabi-v7a/octomap/armeabi-v7a/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/armeabi-v7a/octomap/armeabi-v7a/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/armeabi-v7a/octomap/armeabi-v7a/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86/octomap/x86/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86/octomap/x86/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86/octomap/x86/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86/octomap/x86/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.20)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget octomath octomath-static octomap octomap-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target octomath
add_library(octomath SHARED IMPORTED)

# Create imported target octomath-static
add_library(octomath-static STATIC IMPORTED)

# Create imported target octomap
add_library(octomap SHARED IMPORTED)

set_target_properties(octomap PROPERTIES
  INTERFACE_LINK_LIBRARIES "octomath"
)

# Create imported target octomap-static
add_library(octomap-static STATIC IMPORTED)

# Import target "octomath" for configuration "Debug"
set_property(TARGET octomath APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86_64/octomap/x86_64/liboctomath.so"
  IMPORTED_SONAME_DEBUG "liboctomath.so"
  )

# Import target "octomath-static" for configuration "Debug"
set_property(TARGET octomath-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomath-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86_64/octomap/x86_64/liboctomath.a"
  )

# Import target "octomap" for configuration "Debug"
set_property(TARGET octomap APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap PROPERTIES
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86_64/octomap/x86_64/liboctomap.so"
  IMPORTED_SONAME_DEBUG "liboctomap.so"
  )

# Import target "octomap-static" for configuration "Debug"
set_property(TARGET octomap-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(octomap-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/songdingmao/Projects/jifei/mapbox/mapbox-maps-android/app/.cxx/Debug/4x6m5p40/x86_64/octomap/x86_64/liboctomap.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
